### ISSUE TITLE
improve setting woffMetaDataDescription

### ISSUE THREAD

**Issue by typemytype** [robotools/defconAppKit#26]
when setting the url field and no text is set it fails hard

see https://forum.robofont.com/topic/566/fontinfo-woff-description-url

**Comment by typemytype** [comment]
the ufoLib woffMetadataDescription validator requires both `url` as `text` keys, only one is provided while setting the url value.

maybe the validator must be less strict on requiring the `text` keyword, see https://github.com/anthrotype/ufoLib/blob/master/Lib/ufoLib/validators.py#L378

other woff info attributes dont require the `text` keyword (see [fontInfoWOFFMetadataLicenseValidator](https://github.com/anthrotype/ufoLib/blob/master/Lib/ufoLib/validators.py#L386)) which is basically the same from data structure.

Should I open an issue on fontTools.ufoLib?

@typesupply @anthrotype

**Comment by typemytype** [comment]
the patch could be:

(replaces https://github.com/anthrotype/ufoLib/blob/master/Lib/ufoLib/validators.py#L374-L384 )

```python
def fontInfoWOFFMetadataDescriptionValidator(value):
	"""
	Version 3+.
	"""
	dictPrototype = dict(url=(basestring, False), text=(list, False))
	if not genericDictValidator(value, dictPrototype):
		return False
	if "text" in value:
		for text in value["text"]:
			if not fontInfoWOFFMetadataTextValue(text):
				return False
	return True
```

I can make an fontTool PR if you like

**Comment by typemytype** [comment]
closing the issue here in as this has moved to fontTools ufoLib

https://github.com/fonttools/fonttools/issues/1471

**Comment by benkiel** [comment]
Reading the WOFF spec, the `url` element is optional, but one or more `text` elements is required if setting the description element.

**Comment by typemytype** [comment]
need to refactor the `woffMetaDataDescription` control:

options are (the problem is you can not set multiple things at the same time, since that is galaxtically in space and time just not possible):

* add default entry when a url is given? 
* only set the url when there is entry? 
* the url is as default disabled as long as text is empty (so nothing can be set)
