### ISSUE TITLE
FontInfo window to narrow for expected ps Blue Values

### ISSUE THREAD

**Issue by frankrolf** [robotools/defconAppKit#35]
It is possible to have a total of 7 postscriptBlueValues, which results in a list of 14 number pairs.
[This line](https://github.com/robotools/defconAppKit/blob/4fe38a3956b94a0de1993ea16f723f318776f479/Lib/defconAppKit/controls/fontInfoView.py#L2454) indicates that this amount is in fact expected, however I regularly experience overflow. Here is a typical list of numbers:
`-16 0 516 528 532 544 551 563 628 640 652 668 710 722`

**Comment by typemytype** [comment]
or an indicator if the textfiels has overflow like the default `...` where there is to much text

**Comment by typemytype** [comment]
all info textEdit inputs could be truncated... 

<img width="468" alt="Screen Shot 2020-04-23 at 23 08 35" src="https://user-images.githubusercontent.com/1190358/80149696-5cc2c880-85b7-11ea-808a-f5bfc62379de.png">
